(function () {
  "use strict";

  function wikiThumbFrom960(url) {
    if (!url || !url.includes("upload.wikimedia.org") || !url.includes("/thumb/")) return url;
    return url.replace(/\/\d+px-/, "/330px-");
  }

  function instantWork(id, title, artist, date, url960, desc) {
    const thumb = wikiThumbFrom960(url960);
    return {
      id: `instant:${id}`,
      title,
      artist,
      date,
      description: desc || `${title} — ${artist}`,
      source: "instant",
      thumb_url: thumb,
      preview_url: url960,
      image_url: url960,
      direct_thumb_url: thumb,
      direct_preview_url: url960,
      direct_image_url: url960,
      lqip: ""
    };
  }

  const U = {
    starry: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/960px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    mona: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/960px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
    scream: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/960px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",
    guernica: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Guernica.jpg/960px-Guernica.jpg",
    venus: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/960px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    adam: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/960px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg",
    pearl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/960px-1665_Girl_with_a_Pearl_Earring.jpg",
    lilies: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Claude_Monet_-_Water_Lilies_-_Google_Art_Project.jpg/960px-Claude_Monet_-_Water_Lilies_-_Google_Art_Project.jpg",
    wave: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Tsunami_by_hokusai_19th_century.jpg/960px-Tsunami_by_hokusai_19th_century.jpg",
    gothic: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/960px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg",
    liberty: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/La_Libert%C3%A9_guidant_le_peuple_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_RF_129_-_apr%C3%A8s_restauration_2024.jpg/960px-La_Libert%C3%A9_guidant_le_peuple_-_Eug%C3%A8ne_Delacroix_-_Mus%C3%A9e_du_Louvre_Peintures_RF_129_-_apr%C3%A8s_restauration_2024.jpg",
    school: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/960px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
    haywain: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/John_Constable_-_The_Hay_Wain_%281821%29.jpg/960px-John_Constable_-_The_Hay_Wain_%281821%29.jpg",
    sunrise: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/960px-Monet_-_Impression%2C_Sunrise.jpg",
    gleaners: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project_2.jpg/960px-Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project_2.jpg",
    nighthawks: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/960px-Nighthawks_by_Edward_Hopper_1942.jpg",
    dance: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Renoir%2C_Pierre-Auguste_-_Dance_at_Le_Moulin_de_la_Galette%2C_1876.jpg/960px-Renoir%2C_Pierre-Auguste_-_Dance_at_Le_Moulin_de_la_Galette%2C_1876.jpg",
    nightwatch: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/La_ronda_de_noche%2C_por_Rembrandt_van_Rijn.jpg/960px-La_ronda_de_noche%2C_por_Rembrandt_van_Rijn.jpg",
    garden: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Garden_of_earthly_delights.jpg/960px-The_Garden_of_earthly_delights.jpg",
    thirdmay: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg/960px-El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_thin_black_margin.jpg",
    cafe: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Vincent-van-gogh-cafe-terrace-on-the-place-du-forum-arles-at-night-the.jpg/960px-Vincent-van-gogh-cafe-terrace-on-the-place-du-forum-arles-at-night-the.jpg",
    arnolfini: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/960px-Van_Eyck_-_Arnolfini_Portrait.jpg",
    cards: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Les_Joueurs_de_cartes%2C_par_Paul_C%C3%A9zanne.jpg/960px-Les_Joueurs_de_cartes%2C_par_Paul_C%C3%A9zanne.jpg",
    sunflowers: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_Willem_van_Gogh_-_Sunflowers_-_VGM_F458.jpg/960px-Vincent_Willem_van_Gogh_-_Sunflowers_-_VGM_F458.jpg",
    irises: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Irises-Vincent_van_Gogh.jpg/960px-Irises-Vincent_van_Gogh.jpg",
    cezApples: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Paul_C%C3%A9zanne_-_Still_life_with_apples_-_Google_Art_Project.jpg/960px-Paul_C%C3%A9zanne_-_Still_life_with_apples_-_Google_Art_Project.jpg",
    cezBasket: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Paul_C%C3%A9zanne_-_The_Basket_of_Apples_-_Google_Art_Project.jpg/960px-Paul_C%C3%A9zanne_-_The_Basket_of_Apples_-_Google_Art_Project.jpg",
    cezSkull: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Paul_C%C3%A9zanne_-_Still_life_with_skull_-_Google_Art_Project.jpg/960px-Paul_C%C3%A9zanne_-_Still_life_with_skull_-_Google_Art_Project.jpg",
    cezOranges: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Paul_C%C3%A9zanne_-_Still_Life_with_Apples_and_Oranges_-_Google_Art_Project.jpg/960px-Paul_C%C3%A9zanne_-_Still_Life_with_Apples_and_Oranges_-_Google_Art_Project.jpg",
    zurbaran: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Francisco_de_Zurbar%C3%A1n_-_Still_Life_with_Lemons%2C_Oranges_and_a_Rose_-_Google_Art_Project.jpg/960px-Francisco_de_Zurbar%C3%A1n_-_Still_Life_with_Lemons%2C_Oranges_and_a_Rose_-_Google_Art_Project.jpg",
    chardin: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Jean-Baptiste-Sim%C3%A9on_Chardin_-_The_Mound_of_Butter_-_Google_Art_Project.jpg/960px-Jean-Baptiste-Sim%C3%A9on_Chardin_-_The_Mound_of_Butter_-_Google_Art_Project.jpg",
    vgNovels: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Vincent_van_Gogh_-_Still_Life_with_French_Novels_and_Rose_-_Google_Art_Project.jpg/960px-Vincent_van_Gogh_-_Still_Life_with_French_Novels_and_Rose_-_Google_Art_Project.jpg",
    vgCoffee: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Vincent_van_Gogh_-_Still_Life_with_Coffee_Pot_-_Google_Art_Project.jpg/960px-Vincent_van_Gogh_-_Still_Life_with_Coffee_Pot_-_Google_Art_Project.jpg",
    vgCabbage: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Vincent_van_Gogh_-_Still_life_with_cabbage_and_clogs_-_Google_Art_Project.jpg/960px-Vincent_van_Gogh_-_Still_life_with_cabbage_and_clogs_-_Google_Art_Project.jpg",
    monetChrys: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Claude_Monet_-_Chrysanthemums_-_Google_Art_Project.jpg/960px-Claude_Monet_-_Chrysanthemums_-_Google_Art_Project.jpg",
    fantin: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Henri_Fantin-Latour_-_Still_Life_with_Flowers_and_Fruit_-_Google_Art_Project.jpg/960px-Henri_Fantin-Latour_-_Still_Life_with_Flowers_and_Fruit_-_Google_Art_Project.jpg",
    matisse: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Henri_Matisse_-_Still_Life_with_Geranium_-_Google_Art_Project.jpg/960px-Henri_Matisse_-_Still_Life_with_Geranium_-_Google_Art_Project.jpg",
    gauguin: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Paul_Gauguin_-_Still_Life_with_Sunflowers_on_an_Armchair_-_Google_Art_Project.jpg/960px-Paul_Gauguin_-_Still_Life_with_Sunflowers_on_an_Armchair_-_Google_Art_Project.jpg",
    deHeem: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Jan_Davidsz._de_Heem_-_Still-Life_with_Fruit_and_Ham_-_Google_Art_Project.jpg/960px-Jan_Davidsz._de_Heem_-_Still-Life_with_Fruit_and_Ham_-_Google_Art_Project.jpg",
    melendez: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Luis_Mel%C3%A9ndez_-_Still_Life_with_Melon_and_Peaches_-_Google_Art_Project.jpg/960px-Luis_Mel%C3%A9ndez_-_Still_Life_with_Melon_and_Peaches_-_Google_Art_Project.jpg",
    ruysch: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Rachel_Ruysch_-_Flower_Still-Life_-_Google_Art_Project.jpg/960px-Rachel_Ruysch_-_Flower_Still-Life_-_Google_Art_Project.jpg",
    heda: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Willem_Claesz._Heda_-_Still_Life_with_Oysters_-_Google_Art_Project.jpg/960px-Willem_Claesz._Heda_-_Still_Life_with_Oysters_-_Google_Art_Project.jpg",
    soup: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg/960px-Campbell%27s_Soup_Cans_by_Andy_Warhol.jpg"
  };

  window.ART_INSTANT_BY_GENRE = {
    masterpiece: [
      instantWork("ms-01", "The Starry Night", "Vincent van Gogh", "1889", U.starry),
      instantWork("ms-02", "Mona Lisa", "Leonardo da Vinci", "c. 1503", U.mona),
      instantWork("ms-03", "The Scream", "Edvard Munch", "1893", U.scream),
      instantWork("ms-04", "Guernica", "Pablo Picasso", "1937", U.guernica),
      instantWork("ms-05", "The Birth of Venus", "Sandro Botticelli", "c. 1484", U.venus),
      instantWork("ms-06", "Girl with a Pearl Earring", "Johannes Vermeer", "c. 1665", U.pearl),
      instantWork("ms-07", "Water Lilies", "Claude Monet", "1914", U.lilies),
      instantWork("ms-08", "The Great Wave off Kanagawa", "Katsushika Hokusai", "c. 1831", U.wave),
      instantWork("ms-09", "American Gothic", "Grant Wood", "1930", U.gothic),
      instantWork("ms-10", "Cafe Terrace at Night", "Vincent van Gogh", "1888", U.cafe),
      instantWork("ms-11", "The Creation of Adam", "Michelangelo", "c. 1511", U.adam),
      instantWork("ms-12", "The School of Athens", "Raphael", "1509", U.school),
      instantWork("ms-13", "Liberty Leading the People", "Eugène Delacroix", "1830", U.liberty),
      instantWork("ms-14", "The Night Watch", "Rembrandt", "1642", U.nightwatch),
      instantWork("ms-15", "The Hay Wain", "John Constable", "1821", U.haywain),
      instantWork("ms-16", "Impression, Sunrise", "Claude Monet", "1872", U.sunrise),
      instantWork("ms-17", "Nighthawks", "Edward Hopper", "1942", U.nighthawks),
      instantWork("ms-18", "Dance at Le Moulin de la Galette", "Pierre-Auguste Renoir", "1876", U.dance),
      instantWork("ms-19", "The Gleaners", "Jean-François Millet", "1857", U.gleaners),
      instantWork("ms-20", "The Third of May 1808", "Francisco Goya", "1814", U.thirdmay)
    ],
    history: [
      instantWork("hi-01", "The Birth of Venus", "Sandro Botticelli", "c. 1484", U.venus),
      instantWork("hi-02", "The Creation of Adam", "Michelangelo", "c. 1511", U.adam),
      instantWork("hi-03", "The School of Athens", "Raphael", "1509", U.school),
      instantWork("hi-04", "Liberty Leading the People", "Eugène Delacroix", "1830", U.liberty),
      instantWork("hi-05", "The Third of May 1808", "Francisco Goya", "1814", U.thirdmay),
      instantWork("hi-06", "The Garden of Earthly Delights", "Hieronymus Bosch", "c. 1490", U.garden),
      instantWork("hi-07", "Guernica", "Pablo Picasso", "1937", U.guernica),
      instantWork("hi-08", "The Night Watch", "Rembrandt", "1642", U.nightwatch),
      instantWork("hi-09", "The Starry Night", "Vincent van Gogh", "1889", U.starry),
      instantWork("hi-10", "The Scream", "Edvard Munch", "1893", U.scream),
      instantWork("hi-11", "Mona Lisa", "Leonardo da Vinci", "c. 1503", U.mona),
      instantWork("hi-12", "American Gothic", "Grant Wood", "1930", U.gothic),
      instantWork("hi-13", "Water Lilies", "Claude Monet", "1914", U.lilies),
      instantWork("hi-14", "The Great Wave off Kanagawa", "Katsushika Hokusai", "c. 1831", U.wave),
      instantWork("hi-15", "Cafe Terrace at Night", "Vincent van Gogh", "1888", U.cafe),
      instantWork("hi-16", "The Hay Wain", "John Constable", "1821", U.haywain),
      instantWork("hi-17", "Impression, Sunrise", "Claude Monet", "1872", U.sunrise),
      instantWork("hi-18", "The Gleaners", "Jean-François Millet", "1857", U.gleaners),
      instantWork("hi-19", "Nighthawks", "Edward Hopper", "1942", U.nighthawks),
      instantWork("hi-20", "Dance at Le Moulin de la Galette", "Pierre-Auguste Renoir", "1876", U.dance)
    ],
    portrait: [
      instantWork("po-01", "Mona Lisa", "Leonardo da Vinci", "c. 1503", U.mona),
      instantWork("po-02", "Girl with a Pearl Earring", "Johannes Vermeer", "c. 1665", U.pearl),
      instantWork("po-03", "American Gothic", "Grant Wood", "1930", U.gothic),
      instantWork("po-04", "The Night Watch", "Rembrandt", "1642", U.nightwatch),
      instantWork("po-05", "The Arnolfini Portrait", "Jan van Eyck", "1434", U.arnolfini),
      instantWork("po-06", "The Scream", "Edvard Munch", "1893", U.scream),
      instantWork("po-07", "The Starry Night", "Vincent van Gogh", "1889", U.starry),
      instantWork("po-08", "Cafe Terrace at Night", "Vincent van Gogh", "1888", U.cafe),
      instantWork("po-09", "The Birth of Venus", "Sandro Botticelli", "c. 1484", U.venus),
      instantWork("po-10", "Water Lilies", "Claude Monet", "1914", U.lilies),
      instantWork("po-11", "Liberty Leading the People", "Eugène Delacroix", "1830", U.liberty),
      instantWork("po-12", "The School of Athens", "Raphael", "1509", U.school),
      instantWork("po-13", "The Creation of Adam", "Michelangelo", "c. 1511", U.adam),
      instantWork("po-14", "The Gleaners", "Jean-François Millet", "1857", U.gleaners),
      instantWork("po-15", "Nighthawks", "Edward Hopper", "1942", U.nighthawks),
      instantWork("po-16", "Dance at Le Moulin de la Galette", "Pierre-Auguste Renoir", "1876", U.dance),
      instantWork("po-17", "The Card Players", "Paul Cézanne", "c. 1890", U.cards),
      instantWork("po-18", "The Hay Wain", "John Constable", "1821", U.haywain),
      instantWork("po-19", "Impression, Sunrise", "Claude Monet", "1872", U.sunrise),
      instantWork("po-20", "The Third of May 1808", "Francisco Goya", "1814", U.thirdmay)
    ],
    landscape: [
      instantWork("la-01", "The Starry Night", "Vincent van Gogh", "1889", U.starry),
      instantWork("la-02", "Water Lilies", "Claude Monet", "1914", U.lilies),
      instantWork("la-03", "The Great Wave off Kanagawa", "Katsushika Hokusai", "c. 1831", U.wave),
      instantWork("la-04", "The Hay Wain", "John Constable", "1821", U.haywain),
      instantWork("la-05", "Impression, Sunrise", "Claude Monet", "1872", U.sunrise),
      instantWork("la-06", "Cafe Terrace at Night", "Vincent van Gogh", "1888", U.cafe),
      instantWork("la-07", "The Garden of Earthly Delights", "Hieronymus Bosch", "c. 1490", U.garden),
      instantWork("la-08", "Liberty Leading the People", "Eugène Delacroix", "1830", U.liberty),
      instantWork("la-09", "The Third of May 1808", "Francisco Goya", "1814", U.thirdmay),
      instantWork("la-10", "Nighthawks", "Edward Hopper", "1942", U.nighthawks),
      instantWork("la-11", "The Gleaners", "Jean-François Millet", "1857", U.gleaners),
      instantWork("la-12", "Dance at Le Moulin de la Galette", "Pierre-Auguste Renoir", "1876", U.dance),
      instantWork("la-13", "The Birth of Venus", "Sandro Botticelli", "c. 1484", U.venus),
      instantWork("la-14", "Guernica", "Pablo Picasso", "1937", U.guernica),
      instantWork("la-15", "Mona Lisa", "Leonardo da Vinci", "c. 1503", U.mona),
      instantWork("la-16", "American Gothic", "Grant Wood", "1930", U.gothic),
      instantWork("la-17", "The Scream", "Edvard Munch", "1893", U.scream),
      instantWork("la-18", "The Night Watch", "Rembrandt", "1642", U.nightwatch),
      instantWork("la-19", "The School of Athens", "Raphael", "1509", U.school),
      instantWork("la-20", "The Creation of Adam", "Michelangelo", "c. 1511", U.adam)
    ],
    genre: [
      instantWork("ge-01", "Nighthawks", "Edward Hopper", "1942", U.nighthawks),
      instantWork("ge-02", "Dance at Le Moulin de la Galette", "Pierre-Auguste Renoir", "1876", U.dance),
      instantWork("ge-03", "The Gleaners", "Jean-François Millet", "1857", U.gleaners),
      instantWork("ge-04", "The Card Players", "Paul Cézanne", "c. 1890", U.cards),
      instantWork("ge-05", "Cafe Terrace at Night", "Vincent van Gogh", "1888", U.cafe),
      instantWork("ge-06", "American Gothic", "Grant Wood", "1930", U.gothic),
      instantWork("ge-07", "The Night Watch", "Rembrandt", "1642", U.nightwatch),
      instantWork("ge-08", "The Arnolfini Portrait", "Jan van Eyck", "1434", U.arnolfini),
      instantWork("ge-09", "Mona Lisa", "Leonardo da Vinci", "c. 1503", U.mona),
      instantWork("ge-10", "Girl with a Pearl Earring", "Johannes Vermeer", "c. 1665", U.pearl),
      instantWork("ge-11", "The Hay Wain", "John Constable", "1821", U.haywain),
      instantWork("ge-12", "Impression, Sunrise", "Claude Monet", "1872", U.sunrise),
      instantWork("ge-13", "The Starry Night", "Vincent van Gogh", "1889", U.starry),
      instantWork("ge-14", "Water Lilies", "Claude Monet", "1914", U.lilies),
      instantWork("ge-15", "The Scream", "Edvard Munch", "1893", U.scream),
      instantWork("ge-16", "Liberty Leading the People", "Eugène Delacroix", "1830", U.liberty),
      instantWork("ge-17", "The Third of May 1808", "Francisco Goya", "1814", U.thirdmay),
      instantWork("ge-18", "The Birth of Venus", "Sandro Botticelli", "c. 1484", U.venus),
      instantWork("ge-19", "The School of Athens", "Raphael", "1509", U.school),
      instantWork("ge-20", "Guernica", "Pablo Picasso", "1937", U.guernica)
    ],
    still_life: [
      instantWork("sl-01", "Sunflowers", "Vincent van Gogh", "1888", U.sunflowers),
      instantWork("sl-02", "Irises", "Vincent van Gogh", "1889", U.irises),
      instantWork("sl-03", "Still Life with Apples", "Paul Cézanne", "1895", U.cezApples),
      instantWork("sl-04", "The Basket of Apples", "Paul Cézanne", "1893", U.cezBasket),
      instantWork("sl-05", "Still Life with Skull", "Paul Cézanne", "c. 1895", U.cezSkull),
      instantWork("sl-06", "Still Life with Apples and Oranges", "Paul Cézanne", "c. 1899", U.cezOranges),
      instantWork("sl-07", "Still Life with Lemons, Oranges and a Rose", "Francisco de Zurbarán", "1633", U.zurbaran),
      instantWork("sl-08", "The Mound of Butter", "Jean-Baptiste-Siméon Chardin", "c. 1755", U.chardin),
      instantWork("sl-09", "Still Life with French Novels and Rose", "Vincent van Gogh", "1887", U.vgNovels),
      instantWork("sl-10", "Still Life with Coffee Pot", "Vincent van Gogh", "1888", U.vgCoffee),
      instantWork("sl-11", "Still Life with Cabbage and Clogs", "Vincent van Gogh", "1881", U.vgCabbage),
      instantWork("sl-12", "Chrysanthemums", "Claude Monet", "1882", U.monetChrys),
      instantWork("sl-13", "Still Life with Flowers and Fruit", "Henri Fantin-Latour", "1865", U.fantin),
      instantWork("sl-14", "Still Life with Geranium", "Henri Matisse", "1910", U.matisse),
      instantWork("sl-15", "Still Life with Sunflowers on an Armchair", "Paul Gauguin", "1901", U.gauguin),
      instantWork("sl-16", "Still Life with Fruit and Ham", "Jan Davidsz. de Heem", "c. 1650", U.deHeem),
      instantWork("sl-17", "Still Life with Melon and Peaches", "Luis Meléndez", "c. 1770", U.melendez),
      instantWork("sl-18", "Flower Still Life", "Rachel Ruysch", "c. 1710", U.ruysch),
      instantWork("sl-19", "Still Life with Oysters", "Willem Claesz. Heda", "1635", U.heda),
      instantWork("sl-20", "Campbell's Soup Cans", "Andy Warhol", "1962", U.soup)
    ]
  };
})();
