"""NASDAQ-100 · NYSE 시가총액 TOP 100 (바닥매집 스캔 유니버스)."""

from __future__ import annotations

# NASDAQ-100 (2026-06 리밸런스: +ALAB,CRWV,NBIS,RKLB,TER / -CHTR,CTSH,INSM,VRSK,ZS)
NASDAQ_TOP_100: list[tuple[str, str]] = [
    ("NVDA", "NVIDIA"),
    ("GOOGL", "Alphabet A"),
    ("GOOG", "Alphabet C"),
    ("AAPL", "Apple"),
    ("MSFT", "Microsoft"),
    ("AMZN", "Amazon"),
    ("AVGO", "Broadcom"),
    ("TSLA", "Tesla"),
    ("META", "Meta"),
    ("MU", "Micron"),
    ("AMD", "AMD"),
    ("WMT", "Walmart"),
    ("INTC", "Intel"),
    ("ASML", "ASML"),
    ("AMAT", "Applied Materials"),
    ("LRCX", "Lam Research"),
    ("CSCO", "Cisco"),
    ("COST", "Costco"),
    ("KLAC", "KLA"),
    ("ARM", "Arm Holdings"),
    ("NFLX", "Netflix"),
    ("PLTR", "Palantir"),
    ("PANW", "Palo Alto Networks"),
    ("TXN", "Texas Instruments"),
    ("MRVL", "Marvell"),
    ("LIN", "Linde"),
    ("WDC", "Western Digital"),
    ("STX", "Seagate"),
    ("QCOM", "Qualcomm"),
    ("CRWD", "CrowdStrike"),
    ("AMGN", "Amgen"),
    ("ADI", "Analog Devices"),
    ("PEP", "PepsiCo"),
    ("TMUS", "T-Mobile US"),
    ("APP", "AppLovin"),
    ("GILD", "Gilead"),
    ("SHOP", "Shopify"),
    ("ISRG", "Intuitive Surgical"),
    ("BKNG", "Booking Holdings"),
    ("VRTX", "Vertex Pharma"),
    ("SBUX", "Starbucks"),
    ("FTNT", "Fortinet"),
    ("PDD", "PDD Holdings"),
    ("CDNS", "Cadence"),
    ("MAR", "Marriott"),
    ("MNST", "Monster Beverage"),
    ("DDOG", "Datadog"),
    ("CEG", "Constellation Energy"),
    ("ADP", "ADP"),
    ("CSX", "CSX"),
    ("CMCSA", "Comcast"),
    ("ABNB", "Airbnb"),
    ("MELI", "MercadoLibre"),
    ("SNPS", "Synopsys"),
    ("DASH", "DoorDash"),
    ("ADBE", "Adobe"),
    ("ORLY", "O'Reilly Auto"),
    ("MDLZ", "Mondelez"),
    ("AEP", "American Electric Power"),
    ("INTU", "Intuit"),
    ("HON", "Honeywell"),
    ("NXPI", "NXP Semiconductors"),
    ("CTAS", "Cintas"),
    ("ROST", "Ross Stores"),
    ("WBD", "Warner Bros Discovery"),
    ("MPWR", "Monolithic Power"),
    ("REGN", "Regeneron"),
    ("PCAR", "PACCAR"),
    ("BKR", "Baker Hughes"),
    ("FAST", "Fastenal"),
    ("EA", "Electronic Arts"),
    ("XEL", "Xcel Energy"),
    ("FANG", "Diamondback Energy"),
    ("MCHP", "Microchip"),
    ("FER", "Ferrovial"),
    ("EXC", "Exelon"),
    ("TTWO", "Take-Two"),
    ("KDP", "Keurig Dr Pepper"),
    ("CCEP", "Coca-Cola Europacific"),
    ("ODFL", "Old Dominion"),
    ("AXON", "Axon Enterprise"),
    ("IDXX", "IDEXX Labs"),
    ("ADSK", "Autodesk"),
    ("ALNY", "Alnylam"),
    ("PYPL", "PayPal"),
    ("TRI", "Thomson Reuters"),
    ("PAYX", "Paychex"),
    ("ROP", "Roper Technologies"),
    ("MSTR", "Strategy"),
    ("WDAY", "Workday"),
    ("GEHC", "GE HealthCare"),
    ("KHC", "Kraft Heinz"),
    ("DXCM", "DexCom"),
    ("CPRT", "Copart"),
    ("TEAM", "Atlassian"),
    ("CSGP", "CoStar Group"),
    ("ALAB", "Astera Labs"),
    ("CRWV", "CoreWeave"),
    ("NBIS", "Nebius Group"),
    ("RKLB", "Rocket Lab"),
    ("TER", "Teradyne"),
]

# NYSE 시가총액 TOP 100 (BRK.A 제외 · BRK-B 사용)
NYSE_TOP_100: list[tuple[str, str]] = [
    ("TSM", "TSMC"),
    ("LLY", "Eli Lilly"),
    ("BRK-B", "Berkshire Hathaway"),
    ("JPM", "JPMorgan Chase"),
    ("V", "Visa"),
    ("JNJ", "Johnson & Johnson"),
    ("XOM", "Exxon Mobil"),
    ("CAT", "Caterpillar"),
    ("MA", "Mastercard"),
    ("ABBV", "AbbVie"),
    ("ORCL", "Oracle"),
    ("BAC", "Bank of America"),
    ("GE", "GE Aerospace"),
    ("UNH", "UnitedHealth"),
    ("KO", "Coca-Cola"),
    ("HD", "Home Depot"),
    ("PG", "Procter & Gamble"),
    ("MS", "Morgan Stanley"),
    ("CVX", "Chevron"),
    ("HSBC", "HSBC"),
    ("MRK", "Merck"),
    ("GS", "Goldman Sachs"),
    ("GEV", "GE Vernova"),
    ("AZN", "AstraZeneca"),
    ("NVS", "Novartis"),
    ("RY", "Royal Bank of Canada"),
    ("PM", "Philip Morris"),
    ("DELL", "Dell Technologies"),
    ("IBM", "IBM"),
    ("WFC", "Wells Fargo"),
    ("RTX", "RTX"),
    ("C", "Citigroup"),
    ("AXP", "American Express"),
    ("MUFG", "MUFG"),
    ("BABA", "Alibaba"),
    ("GLW", "Corning"),
    ("APH", "Amphenol"),
    ("ANET", "Arista Networks"),
    ("SHEL", "Shell"),
    ("NVO", "Novo Nordisk"),
    ("BHP", "BHP Group"),
    ("TM", "Toyota"),
    ("TD", "TD Bank"),
    ("SAN", "Banco Santander"),
    ("MCD", "McDonald's"),
    ("TMO", "Thermo Fisher"),
    ("NEE", "NextEra Energy"),
    ("SAP", "SAP"),
    ("VZ", "Verizon"),
    ("TTE", "TotalEnergies"),
    ("DE", "Deere"),
    ("BA", "Boeing"),
    ("DIS", "Walt Disney"),
    ("TJX", "TJX"),
    ("ETN", "Eaton"),
    ("BUD", "Anheuser-Busch"),
    ("RIO", "Rio Tinto"),
    ("WELL", "Welltower"),
    ("UNP", "Union Pacific"),
    ("SCHW", "Charles Schwab"),
    ("ABT", "Abbott"),
    ("BLK", "BlackRock"),
    ("UBS", "UBS"),
    ("UBER", "Uber"),
    ("SMFG", "SMFG"),
    ("T", "AT&T"),
    ("SCCO", "Southern Copper"),
    ("BX", "Blackstone"),
    ("PFE", "Pfizer"),
    ("BBVA", "BBVA"),
    ("DHR", "Danaher"),
    ("BTI", "British American Tobacco"),
    ("CB", "Chubb"),
    ("CVS", "CVS Health"),
    ("UL", "Unilever"),
    ("PLD", "Prologis"),
    ("HDB", "HDFC Bank"),
    ("PGR", "Progressive"),
    ("CRM", "Salesforce"),
    ("COP", "ConocoPhillips"),
    ("VRT", "Vertiv"),
    ("COF", "Capital One"),
    ("BMO", "Bank of Montreal"),
    ("LOW", "Lowe's"),
    ("PH", "Parker-Hannifin"),
    ("ENB", "Enbridge"),
    ("MO", "Altria"),
    ("SYK", "Stryker"),
    ("SONY", "Sony"),
    ("SPGI", "S&P Global"),
    ("BMY", "Bristol-Myers Squibb"),
    ("LMT", "Lockheed Martin"),
    ("MFG", "Mizuho Financial"),
    ("SO", "Southern Company"),
    ("TT", "Trane Technologies"),
    ("PWR", "Quanta Services"),
    ("HWM", "Howmet Aerospace"),
    ("BNS", "Bank of Nova Scotia"),
    ("GSK", "GSK"),
    ("IBN", "ICICI Bank"),
]
